# Generated by Django 6.0.2 on 2026-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="visit_type",
            field=models.CharField(
                choices=[("VIDEO_CALL", "Video Call"), ("IN_PERSON", "In-Person")],
                default="VIDEO_CALL",
                max_length=20,
            ),
        ),
    ]
